### ISSUE TITLE
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).

### ISSUE THREAD

**Issue by semirke** [aruno14/speechRecognition#1]
Hi, 
  thanks for your tutorial :)
 Im trying to run sentence.py with my dataset but it wont run on TF 11 on Python 3.6. 
 I couldnt yet figure out the cause :/
 Could you please give me a helping hand? 
 
Thanks!

sentence.py:122: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return [np.array(batch_x_voice), np.array(batch_x_string)], np.array(batch_y_string)
Traceback (most recent call last):
  File "sentence.py", line 161, in <module>
    model.fit(MySequence(X_voice, X_string, Y_string, batch_size), epochs=epochs, steps_per_epoch=len(X_string)//batch_size)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1064, in fit
    steps_per_execution=self._steps_per_execution)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1112, in __init__
    model=model)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 909, in __init__
    **kwargs)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 781, in __init__
    peek = _process_tensorlike(peek)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1016, in _process_tensorlike
    inputs = nest.map_structure(_convert_numpy_and_scipy, inputs)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 659, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/util/nest.py", line 659, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/data_adapter.py", line 1011, in _convert_numpy_and_scipy
    return ops.convert_to_tensor_v2_with_dispatch(x, dtype=dtype)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1405, in convert_to_tensor_v2_with_dispatch
    value, dtype=dtype, dtype_hint=dtype_hint, name=name)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1415, in convert_to_tensor_v2
    as_ref=False)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1540, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 265, in constant
    allow_broadcast=True)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 276, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 301, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/home/semir/keras_tf/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).

Also the startup: 

2021-02-26 11:41:27.372359: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
voice_max_length: 200
2021-02-26 11:41:28.241010: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-26 11:41:28.241466: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-02-26 11:41:28.278295: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.278646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.665GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2021-02-26 11:41:28.278677: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-02-26 11:41:28.280171: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-02-26 11:41:28.280215: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-02-26 11:41:28.280833: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-02-26 11:41:28.280985: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-02-26 11:41:28.282578: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-02-26 11:41:28.282962: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-02-26 11:41:28.283060: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-02-26 11:41:28.283147: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.283502: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.283822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-26 11:41:28.284033: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-26 11:41:28.284237: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-26 11:41:28.284307: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.284618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.665GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2021-02-26 11:41:28.284645: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-02-26 11:41:28.284655: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-02-26 11:41:28.284664: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-02-26 11:41:28.284671: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-02-26 11:41:28.284679: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-02-26 11:41:28.284687: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-02-26 11:41:28.284694: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-02-26 11:41:28.284701: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-02-26 11:41:28.284732: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.285053: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.285365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-26 11:41:28.285396: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-02-26 11:41:28.624714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-02-26 11:41:28.624736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-02-26 11:41:28.624741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-02-26 11:41:28.624853: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.625217: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.625540: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-02-26 11:41:28.625850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10029 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5)
2021-02-26 11:41:28.837430: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
(612, 6, 513)

**Comment by semirke** [comment]
OK, I got it, I had to create fixed size "parts" in audioToTensor.

**Comment by aruno14** [comment]
@semirke Hello,

Thank you to read my tutorial :)
I commited a fix, maybe it is similar to your fix.
Tell me if it works now.

**Comment by semirke** [comment]
Hi !
Oh, thanks for the prompt response. 
May I have a question? Does every record in your dataset have the same length? 
It's strange for me that you use a random wav file to define the model input tensor size.

**Comment by aruno14** [comment]
@semirke 
>May I have a question? Does every record in your dataset have the same length?

Ask anything you want :)
No, all records do not have the same length, but I normalize all the records to voice_max_length (10s) in the voice_max_length() function.
Below code:
```
if len(audio_clean)<audio_length*voice_max_length:
    audio = tf.concat([np.zeros([audio_length*voice_max_length-len(audio_clean)]), audio_clean], 0)
else:
    audio = audio_clean[-(audio_length*voice_max_length):]
```

**Comment by semirke** [comment]
Hmm, I might have some old missunderstanding... 
I had troubles when tried to load a model and use it on different size of tensors. 
Is that alright to use differnet dimension for the same model?

**Comment by aruno14** [comment]
It depends on the model, for example in the `sentence.py` model input is: `(testParts.shape[0], None, None, 1)`
First dimension size is fixed, second and third one are free and last one is fixed. Two dimensions are free because on next layer they are fixed using `Resizing(6, 129)`.

**Comment by semirke** [comment]
Yes, but it IS shape[0] that changes according to the voice length, isnt it?

**Comment by aruno14** [comment]
shape[0] changes in function of the length of the test file (`testParts = audioToTensor(...)`).
All the files including test file length are the same and fixed using `voice_max_length`.
After the model is created, input size is fixed and can not be changed.

**Comment by semirke** [comment]
> All the files including test file length are the same and fixed using `voice_max_length`.

Ah, there is my answer :)
I see now. I think we are on the same page then.
Instead I used a fix shape size that is supposedly longer than any of my voice files. 

Thanks!

**Comment by semirke** [comment]
> 
> 
> @semirke
> 
> > May I have a question? Does every record in your dataset have the same length?
> 
> Ask anything you want :)
> No, all records do not have the same length, but I normalize all the records to voice_max_length (10s) in the voice_max_length() function.
> Below code:
> 
> ```
> if len(audio_clean)<audio_length*voice_max_length:
>     audio = tf.concat([np.zeros([audio_length*voice_max_length-len(audio_clean)]), audio_clean], 0)
> else:
>     audio = audio_clean[-(audio_length*voice_max_length):]
> ```

Hm. 
Actually the shape change happens with 
`    partsCount = len(range(0, len(spectrogram)-part_length, int(part_length/2)))
`

This is what I have for me: 

```
    partsCount = len(range(0, len(spectrogram)-part_length, int(part_length/2)))
    if(partsCount> 2000):
        print("MAX PCNT REACHED: " + str(partsCount))
    partsCount = 2000
    parts = np.zeros((partsCount, part_length, 513))
    for i, p in enumerate(range(0, len(spectrogram)-part_length, int(part_length/2))):
        if i >= partsCount:
            break
        part = np.array(spectrogram[p:p+part_length])
        parts[i] = part
    return parts

```
However, Im not sure if this'll work out as I expect.
